<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ShortUrlForm.proto

namespace Shortener\ShortUrl\Form;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Shortener.ShortUrl.Form.ShortUrlForm</code>
 */
class ShortUrlForm extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string longUrl = 1;</code>
     */
    private $longUrl = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $longUrl
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ShortUrlForm::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string longUrl = 1;</code>
     * @return string
     */
    public function getLongUrl()
    {
        return $this->longUrl;
    }

    /**
     * Generated from protobuf field <code>string longUrl = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setLongUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->longUrl = $var;

        return $this;
    }

}

