version: "3"

services:
  database:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker/database/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-!ChangeMe!}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-app}
      MYSQL_USER: ${MYSQL_USER:-app}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-!ChangeMe!}
    ports:
      - 3306:3306

  php-fpm:
    container_name: php-fpm-ci
    build:
      context: docker/php-fpm-ci
    depends_on:
      - database
    volumes:
      - ./:/var/www
    environment:
      APP_ENV: ${APP_ENV}
      APP_SECRET: ${APP_SECRET}

  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - ./:/var/www
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - php-fpm
    ports:
      - "80:80"
      - "443:443"

  redis:
    image: redis:latest
    ports:
      - "127.0.0.1:${HOST_MACHINE_REDIS_PORT:-6379}:6379"
