<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: FormErrors.proto

namespace GPBMetadata;

class FormErrors
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ae7010a10466f726d4572726f72732e70726f746f121553686f7274656e" .
            "65722e466f726d2e4572726f727322b3010a0a466f726d4572726f727312" .
            "0e0a066572726f727318012003280912410a086368696c6472656e180220" .
            "03280b322f2e53686f7274656e65722e466f726d2e4572726f72732e466f" .
            "726d4572726f72732e4368696c6472656e456e7472791a520a0d4368696c" .
            "6472656e456e747279120b0a036b657918012001280912300a0576616c75" .
            "6518022001280b32212e53686f7274656e65722e466f726d2e4572726f72" .
            "732e466f726d4572726f72733a023801620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

