<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ShortUrlForm.proto

namespace GPBMetadata;

class ShortUrlForm
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a560a1253686f727455726c466f726d2e70726f746f121753686f727465" .
            "6e65722e53686f727455726c2e466f726d221f0a0c53686f727455726c46" .
            "6f726d120f0a076c6f6e6755726c180120012809620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

