<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ShortUrl.proto

namespace GPBMetadata;

class ShortUrl
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a5b0a0e53686f727455726c2e70726f746f121253686f7274656e65722e" .
            "53686f727455726c222d0a0853686f727455726c120f0a07737563636573" .
            "7318012001280812100a0873686f727455726c180220012809620670726f" .
            "746f33"
        ));

        static::$is_initialized = true;
    }
}

