<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ShortUrl.proto

namespace Shortener\ShortUrl;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Shortener.ShortUrl.ShortUrl</code>
 */
class ShortUrl extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool success = 1;</code>
     */
    private $success = false;
    /**
     * Generated from protobuf field <code>string shortUrl = 2;</code>
     */
    private $shortUrl = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $success
     *     @type string $shortUrl
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ShortUrl::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool success = 1;</code>
     * @return bool
     */
    public function getSuccess()
    {
        return $this->success;
    }

    /**
     * Generated from protobuf field <code>bool success = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setSuccess($var)
    {
        GPBUtil::checkBool($var);
        $this->success = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string shortUrl = 2;</code>
     * @return string
     */
    public function getShortUrl()
    {
        return $this->shortUrl;
    }

    /**
     * Generated from protobuf field <code>string shortUrl = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setShortUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->shortUrl = $var;

        return $this;
    }

}

